name: README build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '21.6.1'
      - name: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Compile typescript
        run: npm run build
      - name: Generate README file
        run: node .
        env:
          API42_UID: ${{secrets.API42_UID}}
          API42_SECRET: ${{secrets.API42_SECRET}}
      - name: Push new README.md
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README.md" || echo "Nothing to push"
          git push
